version: '2'
services:
  applications:
    image: tianon/true
    volumes:
    - ../:/opt/app
  node:
    build: ./node
    environment:
      MYSQL_URL: mysql://root:root@mysql:3306/nodedock
    volumes_from:
      - applications
    depends_on:
      - mysql
    ports:
      - "3000:3000"
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedock
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    build: ./redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
